name: class_app
description: A Flutter app displaying street maps

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: any
  latlong2: any
  http: any
  dio: ^5.3.2
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.1
  geolocator: ^10.1.0
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true